// This file is generated using `list_screen_files.rb`
XS.screens = {
  "molecular_dimensions": {
    "name": "Molecular Dimensions",
    "files": [
      "3DStructure",
      "CSI",
      "CSII",
      "JCSG+ HTS",
      "JCSG+ II",
      "JCSG+",
      "MacroSol I",
      "MacroSol II",
      "MembPlus",
      "MembStart",
      "MembSys",
      "MemGold",
      "midas",
      "miniscreen",
      "Morpheus",
      "NR-LBD",
      "PACT Premier HTS",
      "PACT",
      "PGA_MD",
      "ProPlex",
      "Structure12",
      "Stura Footprint I",
      "Stura Footprint II",
      "Stura+MacroSol HT",
      "UM MembPlus"
    ]
  },
  "qiagen": {
    "name": "Qiagen",
    "files": [
      "AmSO4 Suite",
      "Anions Suite",
      "Cations Suite",
      "Classics II Suite",
      "Classics Lite Suite",
      "Classics Suite",
      "ComPAS Suite",
      "Cryos Suite",
      "CubicPhase I Suite",
      "CubicPhase II Suite",
      "JCSG Core Suite I",
      "JCSG Core Suite II",
      "JCSG Core Suite III",
      "JCSG Core Suite IV",
      "JCSG+ Suite",
      "MbClass I Suite",
      "MbClass II Suite",
      "MPD Suite",
      "Nucleix Suite",
      "Opti-Salts Suite",
      "PACT Suite",
      "PEGs II Suite",
      "PEGs Suite",
      "pHClear II Suite",
      "pHClear Suite",
      "Pre-Screen Assay",
      "Protein Complex Suite"
    ]
  }
}
